LABS-EU3/hackton-backend

api/auth/authModel.js, api/auth/authRouter.js, api/server.js, data/migrations/20191217170254_01-user.js, package.json, utils/generateToken.js, utils/validator.js
create Signup endpoint.
Testing of the endpoint
None
- [*] I have performed a self-review of my own code
- [*] My code follows the style guidelines of this project
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] My changes generate no new warnings
=> Finishes signup endpoint

api/auth/authRouter.js, utils/generateToken.js
create login endpoint
testing of the endpoint
none
- [*] I have performed a self-review of my own code
- [*] My code follows the style guidelines of this project
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] My changes generate no new warnings
=> Finishes login endpoint

api/auth/authModel.js, api/auth/authRouter.js
```
add missen getby function
rename variables in callbacks
```
```
improve error and validations
run server:
`npm run server`
open Postman and hit the following endpoints
`http://localhost:4000/api/auth/login`
data format
```
{
"email": "joewest@yahoo.com",
"password": "123456789"
}
```
`http://localhost:4000/api/auth/register`
data format
```
{
"email": "joewest@yahoo.com",
"password": "123456789"
}
```
- [*] I have performed a self-review of my own code
- [*] My code follows the style guidelines of this project
=> fix error in login functionality

api/auth/authRouter.js
fix bug for Auth0 users not being able to create events
pagination of GET events route
- [*] I have performed a self-review of my own code
- [*] My code follows the style guidelines of this project
=> bug fix for auth0 user to be able to create events

.travis.yml
add codeclimate token to travis.yml file
=> add code climate to travis config

controllers/authUser/authControllers.js, controllers/events/events.spec.js, controllers/eventsCategories/eventsCategory.spec.js, utils/checkInputs.js, utils/requestHandler.js
restructure API response and tests
=> restructure api response and tests

controllers/authUser/authControllers.js
=> refactor auth0 login route

middlewares/CategoryValidator.js, middlewares/EventValidator.js
bugfix for update endpoints `Events and Categories`
=> bug fix on update endpoints for events and categories

routes/auth.js
Add production URL for deployment to production
=> add production url eenv

package.json
add test environment to pretest script
=> add test env to pretest script

controllers/projectGrading/projectGradingControllers.js
Make calls on the controller async
=> make function call in controller async

controllers/projectGrading/projectGradingControllers.js
remove async from promises in grades controllers
=> bug fix average grades

controllers/projects/projectControllers.js
Get all projects for a hackathon and its total score.
=> get each project and its total score

controllers/projects/projectControllers.js
fix grade leakage
remove commented code and console.logs
=> fix grading leakage

controllers/authUser/authModel.js
return user bio from get user query and profile
=> return user bio from user query

controllers/projects/projectControllers.js
refactor grading calculator function to return the number of acted judges and total number of judges for a hackathon
=> refactor grading calculator function

controllers/authUser/authControllers.js, controllers/eventParticipants/eventParticipantsController.js, controllers/eventTeam/eventTeam.spec.js, controllers/eventTeam/eventTeamController.js, controllers/events/eventsControllers.js, controllers/eventsCategories/categoryControllers.js, controllers/projectGrading/projectGrading.spec.js, controllers/projectGrading/projectGradingControllers.js, controllers/projects/projectControllers.js, controllers/projects/projects.spec.js, controllers/users/userController.js, middlewares/CategoryValidator.js, middlewares/EventValidator.js, middlewares/UserValidator.js, models/eventCategoryModel.js, models/eventParticipantsModel.js, models/eventTeamModel.js, models/eventsModel.js, models/projectGradingModel.js, models/projectsModel.js, models/userModel.js, routes/auth.js
=> refactor score aggregate function

config/winston.js, controllers/authUser/authControllers.js, controllers/inviteController/inviteMail.js, data/migrations/20200130230908_confirm-email.js, models/eventParticipantsModel.js, models/eventTeamModel.js, utils/mailHandler.js, utils/reminder.js
configure reminders to only notify verified emails
send email verifycation emails to unvirfied emails on login
silent winston logger when running tests
=> configure reminders to only notify verified emails

controllers/eventParticipants/eventParticipantsController.js, controllers/events/events.spec.js, controllers/events/eventsControllers.js, middlewares/EventValidator.js, models/eventParticipantsModel.js, models/eventsModel.js, routes/events.js
get events participants by user id
[Finishes user get events and participants by user id]
=> get events by user id and events user has signed up for

controllers/authUser/authControllers.js, controllers/inviteController/inviteMail.js
=> fix email call to action buttons for judge invites

controllers/inviteController/inviteMail.js, utils/checkInputs.js
fix email redirect for invites
=> fix email redirect
